"""
backend/gateway/schemas/compliance.py
=======================================
MiFID II / SEC compatible compliance wrappers.

Every advisory response from the AI agent MUST be wrapped in AdvisoryResponse,
which injects mandatory disclaimers and flags the output as AI-generated.
This module is imported by the synthesize_response agent node.
"""

from __future__ import annotations

import os
import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Annotated, Any, Optional

from pydantic import BaseModel, ConfigDict, Field, model_validator


# ---------------------------------------------------------------------------
# Constants — loaded from environment at import time (no hardcoding)
# ---------------------------------------------------------------------------

_MIFID2_DISCLAIMER: str = os.environ.get(
    "MIFID2_DISCLAIMER",
    (
        "This analysis is generated by an AI system and does not constitute "
        "financial advice. Past performance is not indicative of future results. "
        "Please consult a qualified financial advisor before making investment "
        "decisions. Capital at risk."
    ),
)

_SEC_DISCLAIMER: str = os.environ.get(
    "SEC_DISCLAIMER",
    (
        "This material is for informational purposes only and is not intended "
        "as investment advice. The information provided does not take into account "
        "your individual investment objectives, financial situation, or needs."
    ),
)


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class ComplianceFramework(str, Enum):
    """Applicable regulatory framework for the disclaimer."""
    MIFID2 = "MiFID_II"
    SEC = "SEC"
    BOTH = "MiFID_II_and_SEC"


class RiskWarningLevel(str, Enum):
    """Risk severity classification of the advisory content."""
    LOW = "LOW"           # General market information
    MEDIUM = "MEDIUM"     # Portfolio analysis with specific recommendations
    HIGH = "HIGH"         # Specific buy/sell recommendations or rebalancing plans


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------

class ComplianceMetadata(BaseModel):
    """Metadata appended to every advisory output for audit and compliance."""

    model_config = ConfigDict(frozen=True)

    framework: ComplianceFramework
    disclaimer_text: str
    risk_warning_level: RiskWarningLevel
    ai_generated: bool = True
    model_identifier: Optional[str] = None      # e.g. "Qwen2.5-72B-Instruct-AWQ"
    tool_validated: bool = False                  # True if output is backed by Quant Engine
    contains_specific_recommendations: bool = False
    generated_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


class AdvisoryResponse(BaseModel):
    """
    MiFID II / SEC compliant wrapper for all AI advisory outputs.

    Usage — in synthesize_response node:
        return AdvisoryResponse.wrap(
            content=llm_output,
            risk_level=RiskWarningLevel.MEDIUM,
            tool_validated=True,
        )
    """

    model_config = ConfigDict(frozen=True)

    response_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    session_id: str
    intent_class: str
    content: str                          # Main AI-generated advisory text
    tool_data: Optional[Any] = None       # Structured data from Quant Engine tools
    compliance: ComplianceMetadata
    citations: list[str] = Field(
        default_factory=list,
        description="Source document references used in RAG retrieval"
    )
    requires_human_confirmation: bool = False
    pending_action_id: Optional[uuid.UUID] = None   # Set when HITL is pending

    @model_validator(mode="after")
    def validate_transactional_consistency(self) -> "AdvisoryResponse":
        """Ensure pending_action_id is set when human confirmation is required."""
        if self.requires_human_confirmation and self.pending_action_id is None:
            raise ValueError(
                "pending_action_id must be set when requires_human_confirmation=True"
            )
        return self

    @classmethod
    def wrap(
        cls,
        *,
        content: str,
        session_id: str,
        intent_class: str,
        risk_level: RiskWarningLevel = RiskWarningLevel.MEDIUM,
        tool_validated: bool = False,
        tool_data: Optional[Any] = None,
        citations: Optional[list[str]] = None,
        model_identifier: Optional[str] = None,
        requires_human_confirmation: bool = False,
        pending_action_id: Optional[uuid.UUID] = None,
        framework: ComplianceFramework = ComplianceFramework.BOTH,
    ) -> "AdvisoryResponse":
        """
        Factory method: wrap raw LLM output in a compliance-enforced response.

        All advisory outputs MUST go through this factory — never construct
        AdvisoryResponse directly in agent node code.
        """
        # Select disclaimer text based on framework
        if framework == ComplianceFramework.MIFID2:
            disclaimer = _MIFID2_DISCLAIMER
        elif framework == ComplianceFramework.SEC:
            disclaimer = _SEC_DISCLAIMER
        else:
            disclaimer = f"{_MIFID2_DISCLAIMER}\n\n{_SEC_DISCLAIMER}"

        compliance = ComplianceMetadata(
            framework=framework,
            disclaimer_text=disclaimer,
            risk_warning_level=risk_level,
            tool_validated=tool_validated,
            model_identifier=model_identifier,
            contains_specific_recommendations=(
                risk_level in {RiskWarningLevel.MEDIUM, RiskWarningLevel.HIGH}
            ),
        )

        return cls(
            session_id=session_id,
            intent_class=intent_class,
            content=content,
            tool_data=tool_data,
            compliance=compliance,
            citations=citations or [],
            requires_human_confirmation=requires_human_confirmation,
            pending_action_id=pending_action_id,
        )


class HITLConfirmationRequest(BaseModel):
    """
    Payload sent to the frontend when a transactional action requires
    human approval before execution.
    """

    model_config = ConfigDict(frozen=True)

    action_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    session_id: str
    action_type: str          # e.g. "execute_order", "rebalance_portfolio"
    action_summary: str       # Human-readable description of the pending action
    action_payload: dict      # Full tool input (for frontend display)
    risk_level: RiskWarningLevel
    expires_at: str           # ISO 8601 — confirmation window (e.g. 5 minutes)
    compliance_note: str = _MIFID2_DISCLAIMER


class HITLConfirmationResponse(BaseModel):
    """
    Frontend submits this after the user approves or rejects a transactional action.
    The signed token proves 2FA completion.
    """

    model_config = ConfigDict(frozen=True)

    action_id: uuid.UUID
    session_id: str
    approved: bool
    confirmation_token: Annotated[str, Field(
        min_length=32,
        description="Signed 2FA token generated by Auth0 MFA flow"
    )]
    user_agent: Optional[str] = None
    ip_address: Optional[str] = None
