"""
backend/gateway/routers/orders.py
===================================
Order execution endpoints.

Endpoints:
  POST /orders/execute       → Execute a paper/live trade (requires HITL token)
  GET  /orders/history       → Retrieve order history
  GET  /orders/positions     → Get current paper portfolio positions
"""

from __future__ import annotations

import logging
import uuid
from typing import Annotated

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException, status

from backend.agents.tools.order_tools import _paper_portfolio, _paper_cash, tool_execute_order
from backend.gateway.middleware.audit import make_audit_task
from backend.gateway.middleware.auth import RequireTrader, TokenPayload
from backend.gateway.schemas.portfolio import ExecutionStatus
from backend.gateway.schemas.tools import ExecuteOrderInput

logger = logging.getLogger(__name__)
router = APIRouter()


@router.post(
    "/execute",
    response_model=ExecutionStatus,
    summary="Execute a trade order (requires confirmed 2FA token)",
)
async def execute_order(
    order: ExecuteOrderInput,
    background_tasks: BackgroundTasks,
    user: Annotated[TokenPayload, RequireTrader],
) -> ExecutionStatus:
    """
    Execute a trade order via the paper trading engine.

    The `confirmation_token` must be a signed token generated by the
    frontend HITL 2FA flow. Orders without a valid token are rejected.

    In production: replace with Alpaca/IBKR adapter while keeping
    the ExecuteOrderInput → ExecutionStatus interface unchanged.
    """
    logger.info(
        "execute_order | user=%s | %s %s %s @ %s",
        user.sub, order.side.value, order.amount, order.asset, order.order_type.value
    )

    result = await tool_execute_order(order)

    background_tasks.add_task(
        make_audit_task(
            user_id=user.sub,
            session_id=str(order.portfolio_id),
            raw_input=f"execute_order {order.side.value} {order.amount} {order.asset}",
            intent_class="TRANSACTIONAL",
            tool_payload={
                "order_id": str(result.order_id),
                "asset": order.asset,
                "side": order.side.value,
                "amount": str(order.amount),
                "status": result.status.value,
                "fill_price": str(result.fill_price) if result.fill_price else None,
            },
            is_transactional=True,
        )
    )

    return result


@router.get(
    "/positions",
    summary="Get current paper portfolio positions",
)
async def get_positions(
    user: Annotated[TokenPayload, RequireTrader],
) -> dict:
    """Return current paper portfolio positions and cash balance."""
    return {
        "cash_usd": float(_paper_cash),
        "positions": {
            ticker: float(qty)
            for ticker, qty in _paper_portfolio.items()
            if qty > 0
        },
    }
